"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-06 15:31:35.566823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_external_id'), 'player', ['external_id'], unique=True)
    op.create_table('scraperun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('validation_errors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_snapshot_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playersnapshot',
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('market_value', sa.Integer(), nullable=False),
    sa.Column('ideal_bid', sa.Integer(), nullable=True),
    sa.Column('max_bid', sa.Integer(), nullable=True),
    sa.Column('price_change_abs', sa.Integer(), nullable=True),
    sa.Column('price_change_pct', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('price_per_point', sa.Float(), nullable=True),
    sa.Column('starter_probability', sa.Float(), nullable=True),
    sa.Column('availability_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_opponent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_fields', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scraperun.id'], ),
    sa.PrimaryKeyConstraint('as_of', 'player_id')
    )
    op.create_table('rawscrape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('html', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scraperun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rawscrape')
    op.drop_table('playersnapshot')
    op.drop_table('scraperun')
    op.drop_index(op.f('ix_player_external_id'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
