"""make stat counter fields nullable

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-14 13:11:24.121918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playerseasonstats', 'goals',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'goal_assist',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'offtarget_att_assist',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'total_scoring_att',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'pen_area_entries',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'penalty_won',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'penalty_save',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'penalty_failed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'penalty_conceded',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'saves',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'effective_clearance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'own_goals',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'goals_conceded',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'won_contest',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'ball_recovery',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'poss_lost_all',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'yellow_card',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'second_yellow_card',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'red_card',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'mins_played',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playerseasonstats', 'marca_points',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playerseasonstats', 'marca_points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'mins_played',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'red_card',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'second_yellow_card',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'yellow_card',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'poss_lost_all',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'ball_recovery',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'won_contest',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'goals_conceded',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'own_goals',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'effective_clearance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'saves',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'penalty_conceded',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'penalty_failed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'penalty_save',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'penalty_won',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'pen_area_entries',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'total_scoring_att',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'offtarget_att_assist',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'goal_assist',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playerseasonstats', 'goals',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
