"""GET /api/models/market/* — our next-market-update predictions (MODEL-01),
their track record (MODEL-03) and where they disagree with the source's
(MODEL-04). Read-only: predictions are generated by the refresh."""

from datetime import date
from typing import Literal

from fastapi import APIRouter

from api.deps import SessionDep
from storage.our_models import (
    divergence_payload,
    market_predictions_payload,
    track_record_payload,
)

router = APIRouter()


@router.get("/models/market/predictions")
def market_predictions(session: SessionDep, madeOn: date | None = None):  # noqa: N803
    return market_predictions_payload(session, madeOn)


@router.get("/models/market/track-record")
def market_track_record(
    session: SessionDep, version: Literal["market-v1", "market-v2"] = "market-v1"
):
    return track_record_payload(session, version)


@router.get("/models/market/divergence")
def market_divergence(session: SessionDep):
    return divergence_payload(session)
